"""create posts table

Revision ID: 25890e899e87
Revises: 3f191955a29d
Create Date: 2026-07-12 22:50:26.393353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25890e899e87'
down_revision: Union[str, Sequence[str], None] = '3f191955a29d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=2048), nullable=True),
    sa.Column('visibility', sa.Enum('PUBLIC', 'PRIVATE', name='post_visibility'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_posts_author_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_posts'))
    )
    op.create_index('ix_posts_author_created_at', 'posts', ['author_id', 'created_at'], unique=False)
    op.create_index('ix_posts_visibility_created_at', 'posts', ['visibility', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_posts_visibility_created_at', table_name='posts')
    op.drop_index('ix_posts_author_created_at', table_name='posts')
    op.drop_table('posts')
    # ### end Alembic commands ###
